language: java
jdk:
  - openjdk11

before_install:
 - chmod +x mvnw
 
cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw clean test
  
after_success:
  - mvn clean test jacoco:report coveralls:jacoco
